name = "zrh-field-leads"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "zrh-field-leads.maurinwidmer.workers.dev/submit", zone_name = "maurinwidmer.workers.dev" }
]
